version: '3.8'
services:
  rode-battle-socket:
    container_name: rode-battle-socket-management
    image: ${DOCKER_HUB_URL}/rode-be-socket:nightly
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${PORT}
      PUBLIC_CORS_DOMAIN: ${PUBLIC_CORS_DOMAIN}
      LOCAL_CORS_DOMAIN: ${LOCAL_CORS_DOMAIN}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRED_IN: ${JWT_EXPIRED_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRED_IN: ${JWT_REFRESH_EXPIRED_IN}

      PUBLIC_TEST_CASE_COUNT: ${PUBLIC_TEST_CASE_COUNT}
      SUBMIT_TIME_OUT: ${SUBMIT_TIME_OUT}

      GOOGLE_CLIENT_EMAIL: ${GOOGLE_CLIENT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY}
      GOOGLE_PRIVATE_KEY_ID: ${GOOGLE_PRIVATE_KEY_ID}