version: '3.8'
services:
  rode-battle-socket:
    container_name: rode-battle-socket-management
    image: ${DOCKER_HUB_URL}/rode-be-socket:nightly
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRED_IN: ${JWT_EXPIRED_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRED_IN: ${JWT_REFRESH_EXPIRED_IN}
      PUBLIC_TEST_CASE_COUNT: ${PUBLIC_TEST_CASE_COUNT}
      SERVER_PORT: ${PORT}
      PUBLIC_CORS_DOMAIN: ${PUBLIC_CORS_DOMAIN}
      LOCAL_CORS_DOMAIN: ${LOCAL_CORS_DOMAIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}