name: Build R.ODE Backend Socket
on:
  pull_request:
    branches: ["develop"]

jobs:
  rode-be-socket-clean-code:
    name: Check Clean Code On Pull Request
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Code Quality
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}