on:
  push:
    branches: ["develop", "main"]

jobs:
  socket-build:
    name: Build source code to Docker image
    runs-on: arisa-be-socket
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Image And Push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            DB_URL=postgres://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@anataarisa.hopto.org/rode-be-test
          push: true
          tags: ${{ secrets.DOCKER_USER }}/rode-be-socket:${{ github.ref_name == 'main' && 'stable' || 'nightly' }}